DOLConfig/serverconfig_extraproperties.xml, GameServer/GameServer.cs, GameServer/GameServerConfiguration.cs, GameServer/commands/gmcommands/Instance.cs, GameServer/commands/gmcommands/merchant.cs, GameServer/commands/gmcommands/mob.cs, GameServer/commands/gmcommands/object.cs, GameServer/gameobjects/GameLiving.cs, GameServer/gameobjects/GameNPC.cs, GameServer/gameutils/ScriptMgr.cs, GameServer/quests/QuestsMgr/QuestMgr.cs, GameServer/world/Instance/Instance.cs
Update: Add a new Config for preventing Game Server Scripts Compilation (Allowing to plug a debugger)
Improve ScriptMgr Assemblies Accessors for Enumeration of Ordered Core/Script Assembly
Replacing most Assembly gathering from other classes to use these new accessors.
=> Config option preventing GameServerScript compilation to plug a debugger

GameServer/SimpleScheduler.cs, GameServer/managers/worldmanager/WeatherManager.cs
Stopping a Task on SimpleScheduler is Locking the Task waiting for thread to Complete.
This can Lead to deadlock in Weather Manager when accessing Region Dictionary.
=> Fix: Prevent Deadlock in WeatherManager when Stopping Weather Tasks.

GameServer/GlobalConstants.cs, GameServer/gameutils/SkillBase.cs, GameServer/propertycalc/StatCalculator.cs
1: Adds Mythical Stat Cap bonuses to GlobalConstants
2: Adds references in SkillBase to show properly on item info
3: Formula additions/changes to StatCalculator to be properly affected by the new mythicals to live-like standards
Signed-off-by: Mannik/Dargon <zbowen1994@gmail.com>
=> Updates: Mythical Stat Bonuses

DOLDatabase/DatabaseParameter.cs, DOLDatabase/Handlers/MySQLObjectDatabase.cs, DOLDatabase/Handlers/SQLiteObjectDatabase.cs, DOLDatabase/ObjectDatabase.cs, DOLDatabase/SQLObjectDatabase.cs
From MySQL documentation the Prepare Statement is ignored by default in ADO.NET connector...
Enabling server-side Prepare needed some logic change in the Parameter Binding, leading to some update of the underlying API.
Server-side Prepare Statement should speed up Bulk Data Access and reduce network overhead when sending Data.
=> Database Patch Enabling Server Side MySQL Prepare

GameServerScripts/startup/script/CreationStartupEquipment.cs
Save Character in Database when switching Active Weapon Slot on Startup Equipment Creation.
Allowing the player to load with the correct weapon slot when hitting start button, ready to use in combat !
=> Creation Startup Equipment Active Weapon Slot Fix

GameServer/keeps/AbstractGameKeep.cs
Fixes a bug introduced from a previous commit. Currently, when claiming
a keep the guild keep count is added twice. Removing this line allows a
guild to claim and release keeps, and claim again without server reboot.
=> Duplicate claimedkeep entry fix

.travis.yml, GameServer/GameServer.cs, GameServer/GameServer.csproj, GameServer/config/logconfig_unix.xml
Check on Runtime to deploy unix compatible logconfig.xml  (without colored console appender).
Update: Travis configuration remove edition of logconfig prior to running tests.
=> Check on Runtime to deploy unix compatible logconfig.xml 

GameServer/serverrules/AbstractServerRules.cs
Currently, a player who has pvp immunity can still attack mobs, but mob
cant fight back until immune is over. This adds a check and sends player
the denied message. More of an issue for pvp server mode where immunity
timers can be long.
=> Added check for players attacking mobs while immune

GameServer/GlobalConstants.cs, GameServer/gameobjects/CustomNPC/Healer.cs, GameServer/gameobjects/GamePlayer.cs, GameServer/realmabilities/handlers/PerfectRecoveryAbility.cs, GameServer/serverproperty/ServerProperties.cs, GameServer/spells/IllnessSpellHandler.cs, GameServer/spells/ResurrectSpellHandler.cs, GameServer/spells/RvRSicknessSpellHandler.cs
Adds RvR, PvP, and PvE types of resurrection. RvR sickness is not curable except by Perfect recovery RA, and perfecter ML8 ability. PvP sickness player looses 3 con on death, curable. Con loss can be removed in server properties. PvE sickness removes con depending on number of death that level, curable.
=> Adds working resurrection sickness

GameServer/GlobalConstants.cs, GameServer/gameobjects/GameLiving.cs, GameServer/gameobjects/GamePlayer.cs, GameServer/spells/SpellHandler.cs
Fixed Champion Level spells cast speed.
Fixed Champion Level spells effectiveness:
CL specialization level will be returned as 50 again.
CL spell effective level should be calculated correctly again.
Due to changes to the naming of Champion lines the value provided by the global constant would never match. The constant's name has been changed, it's value set to match current CL line naming and an additional string.StartsWith() check has replaced a dysfunctional comparison.
=> Bugfix: Champion Level spell cast speed and effectiveness

GameServer/packets/Client/168/DetailDisplayHandler.cs
Fix for realm ability delve in trainer window. Shows correct info for ability you clicked on instead of the one below it.
=> Fix for realm ability delve

GameServer/gameobjects/GamePlayer.cs
Fixes spelling which mismatches language manager string. Fix backup method giving wrong gender to globalconstants rank listings
=> realm rank title fix

GameServer/packets/Server/PacketLib1119.cs
in 1.119, item.effect in packet was changed to a short. This reflects the change, and allows items to be loaded/moved etc correctly
=> 1119 inventory support

GameServer/gameobjects/Dragons/Cuuldurach.cs, GameServer/gameobjects/Dragons/Gjalpinulva.cs
Cuul and Gjal were using heat for their debuff damagetype, likely due to be copy/pasted from Gole.  Changed to match their glare and breath damage types.
=> Fixed dragon debuff damagetype

GameServer/serverrules/AbstractServerRules.cs
CheckAbilityToUseItem() was using allow_cross_realm_item to bypass item.realm = player.realm checks, but wasn't working for weapons and armour because of the way it determined which ability to check for.
Now, when non-helm armour or a weapon are checked, if allow_cross_realm_item is true, the ability checked is selected based on the player's realm rather than the item's so weapons and armour are actually cross realm now.
=> Fixed allow_cross_realm_item

GameServer/gameobjects/GamePlayer.cs, GameServer/serverproperty/ServerProperties.cs
I hate waiting to quit, so this change checks for ServerProperty "remove quit timer" and lets privlevel 1 accounts quit instantly so long as they aren't in combat.
=> Remove Quit Timer

GameServer/gameobjects/Bonedancer/CommanderPet.cs
Calling CastSpell() with NULL for line causes an exception.
=> Fixed CastSpell() call

GameServer/gameobjects/GameNPC.cs
Added more intelligent style selection.
When styles are loaded, they're sorted into separate lists for defensive styles, styles chained off another style, and positional/anytime styles.
When a style is selected, it checks for possible defensive styles first, chains second, and then checks for positional/anytime styles.  Chain styles skip the GAMENPC_CHANCES_TO_STYLE check, since they'll almost never happen otherwise.  Defensive styles are limited, so a mob with a defensive chain isn't utterly broken.
=> Smarter Style Selection

GameServer/gameobjects/GameLiving.cs
Removed hardcoded efficiency values in functions that should have been using the Efficiency accessor instead.  Modified multiplier to effectiveness to not assume base effectiveness is 1.
This will cause those two lines to properly use overloaded Efficiency accessors from inheriting classes, and causes melee damage of pets to be properly effected by res sickness.
Also removed special characters that always pop up as a change so that doesn't happen in future.
=> Removed hardcoded efficiency values

GameServer/gameobjects/GamePlayer.cs
This exception causes weird server behaviour like mobs vanishing and such, so this changes it to log a warning instead.
=> Changed duraction<1 exception to log entry

GameServer/gameobjects/GameNPC.cs
AutoSetStats() was only being called if all a mobs stats in npctemplate or mob were 0, which led to funkiness like mobs with 0 con and 1 hp that died if sneezed at.
AutoSetStat() is now always called, and check each stat individually to see if it should be set to default, and checks against the original template when doing so in case Level changes.  An offset was added to the stat per level calculations so that a level 1 mob starts with a default physical stats at 30 rather than 31.
Also noticed that GameNPC constructors are rarely called, so I put a comment in about that to warn future devs, and set the two functions that load the NPC to call AutoSetStat(), otherwise it never gets executed.
=> Fix mob stats

GameServer/gameobjects/Bonedancer/CommanderPet.cs, GameServer/gameobjects/CharacterClasses/CharacterClassBase.cs, GameServer/gameobjects/GamePet.cs
This adds a new method, StripOwnerBuffs(), to GamePet, which is called when the pet dies and when a player releases it.
It will stop players from summoning one pet to get buffs, and then releasing it to summon something else while still keeping the buff.
=> Pet cancel buffs

GameServer/ai/brain/StandardMobBrain.cs
I reported this a while back, but it doesn't look like it was remedied: http://www.dolserver.net/viewtopic.php?f=5&t=23087&p=158981&hilit=pet+aggro+through+wall
This is a quick fix rather than resolving the underlying problem.  There may be other issues stemming from the underlying race condition Leo mentions, but fixing that is beyond my capabilities.
=> Stop pets from getting aggro out of LOS

GameServer/gameobjects/GameLiving.cs, GameServer/serverproperty/ServerProperties.cs
This is an old and controversial issue.
At release, Mythic said that Alb weapons did more damage than other realms, at the cost of having to spend more spec points to get there, but tests on live disproves that.  I remember Hib tanks being pissed because once they maxed out parry and spear, they had wasted spec points, while Alb tanks still had useful things to spend points on.  There's still people trying to get Broadsword to change it on live.
Since live still dual specs, the responsible option is a server prop set to dual spec by default.  Let people decide for themselves if they want dual speccing or not.
=> Server prop for Alb weapon dual spec

GameServer/packets/Server/PacketLib1110.cs
siege firing/reloading animation timer changed from (value / 100 ) to just (value).
Fixes catapults/trebs instantly hitting target
=> siege animation fix

GameServer/serverproperty/ServerProperties.cs
In code, the AUTOSET_STR_MULTIPLIER amount is multiplied by 10 when used.  Changing that and making the default 10 rather than 1 would break existing DBs, so I'm instead updating the description so server admins know how it actually works.
=> Updated AUTOSET_STR_MULTIPLIER description

GameServer/spells/Teleport/GatewayPersonalBind.cs
The RVR zone check doesn't make sense for PvE servers, and I don't see any reason for the instance check at all.  If there is a reason for the instance check that I'm not seeing, it's easy enough to change this to still do it.
=> Removed Gateway location check for PvE servers

GameServer/spells/HealSpellHandler.cs
Because amount is a double which is being rounded to an int, sometimes the amount actually healed rounds down, and you end up with the amount to heal being more than the amount actually healed, which triggers the "fully healed" message when it isn't appropriate.
=> Fixed faulty "fully healed" messages

GameServer/gameobjects/GameNPC.cs
Sometimes, mobs will try to fire arrows but due to some gimmick in the math somewhere be just a hair out of range.  This leads to them starting to fire over and over again without actually firing.  It appears to add multiple ranged fire timers, so the moment the target is in range, all the timers go off at once and do a ridiculous amount of burst damage.
By forcing mobs to move just a tiny bit closer before firing, this issue appears to be resolved.
=> Fixed issue with archer mobs at max range

GameServer/keeps/KeepManager.cs
Only checking for PVE, PVP, and normal server types left the others out in the cold when they should be using the default realm check
=> Changed: KeepManager.IsEnemy() works for all keep types

GameServer/gameobjects/GameNPC.cs, GameServer/keeps/Managers/Template Manager.cs, GameServer/serverproperty/ServerProperties.cs
Stats for keep guards and lord was hardcoded in TemplateManager.  This replaces that with server properties for all guard and lord stats.
The default values are based on the old hard coded values so that guard/lord stats won't change on existing servers.
=> Server props for keep guard stats

GameServer/gameobjects/Bonedancer/CommanderPet.cs, GameServer/gameobjects/GameNPC.cs, GameServer/spells/SummonSpellHandler.cs
These changes allow the brain of pets to be set by the ClassType in their NPCTemplate, and allows the number of subpets BD commanders can summon to be set by the TetherRange of their NPCTemplate.
Not only does this allow databases to add pets like the Dread Lord on live, but it also allows custom servers to create completely new pet behaviour without recompiling by changing which brain pets use or even creating and assigning a completely new scripted brain.
Amusingly enough, formations for a BD commander with 5 subpets are exactly like live; lines get longer and the last two pets stand over the commander for other formations.
Old hardcoded values are still present, so existing servers should not be impacted.
=> Give DB more control over pets

GameServer/housing/HouseTemplateMgr.cs, GameServer/serverrules/AbstractServerRules.cs
Currently you can buy a teleporter to any realm. This is not a good thing. Fixed this unless server type is PvP or PvE.
=> Fix Housing Teleporters

DOLDatabase/IObjectDatabase.cs, DOLDatabase/ObjectDatabase.cs, GameServer/gameobjects/Bonedancer/BDSubPet.cs, GameServer/spells/SpellHandler.cs
This change makes low spec BD pets useful without making them overpowered for the amount the player has invested in them.  It also provides more reason to branch out BD specs and to gear for +skill bonuses.
Currently, pet spell scaling is based entirely on pet level.  If you summon a bone guardian, it will cast the same quality of buffs if you only have 20 spec in suppression as if you spec'd all the way to 50.  That's just not right, and leads to dipping into a secondary spec being more powerful than it should be.  A good example would be a BA BD speccing to 15 in suppression to get the same full damage shield and attack speed buffs they'd get if they were specced to 50 in suppression.  There should be a consequence to that which also provides incentive to spec further into suppression …
=> Scale bd minion effects by player spec

GameServer/commands/gmcommands/keep.cs, GameServer/gameobjects/GameNPC.cs, GameServer/keeps/AbstractGameKeep.cs, GameServer/keeps/GameKeepComponent.cs, GameServer/keeps/Gameobjects/GameKeepBanner.cs, GameServer/keeps/Gameobjects/GameKeepDoor.cs, GameServer/keeps/Gameobjects/Guards/GameKeepGuard.cs, GameServer/keeps/Gameobjects/Guards/Patrol.cs, GameServer/keeps/HookPointInventory.cs, GameServer/keeps/IGameKeep.cs, GameServer/keeps/KeepManager.cs
There is a lot of pattern matching in here, so AppVeyor won't like it.
This started out with me wanting to put in logging to see if I could track down why dolpub is putting multiple lords and other characters in keeps.  I thought the code for GameKeepComponent.FillPositions() was difficult to red and maintain, so I changed it to make it more legible.
While I was there, I figured I may as well optimize code a bit by doing things like using .Add(), Contains(), and Remove() rather than [] on Hashtables, and from there looked for other things I could speed up.  Ultimately, I ended up changing Hashtables to Dictionaries to force proper typing to catch coding errors, and speed things up by removing the boxing and unboxing necessary with Hashtables.
I also found a bunch of small things like key …
=> Report keepitem duplicates & Optimization

GameServer/GlobalConstants.cs, GameServer/gameobjects/CustomNPC/Hastener.cs, GameServer/gameobjects/CustomNPC/Healer.cs, GameServer/gameobjects/CustomNPC/HousingHastener.cs, GameServer/gameobjects/GamePlayer.cs, GameServer/keeps/Gameobjects/Guards/Hastener.cs, GameServer/realmabilities/handlers/PerfectRecoveryAbility.cs, GameServer/spells/IllnessSpellHandler.cs, GameServer/spells/ResurrectSpellHandler.cs, GameServer/spells/RvRSicknessSpellHandler.cs, GameServer/spells/SpeedOfTheRealmHandler.cs
Saves the effects of resurrection illness and Speed of the Realm on player exit and restores them when player logs back in.
Had to move these effects to a different 'globalspellline' as reserved spells are not saved on exit.
=> Resurrection illness and Realm Speed restored

GameServer/housing/HouseTemplateMgr.cs
allows player to purchase a consignment merchant from the housing lot marker after the lot is purchased (along with house type and porch etc) Mainly for convenience.
=> Add Consignment Merchant

GameServer/keeps/Managers/Spell Manager.cs
Currently, Lords have a heal spell which has realm as the target, so they can heal other mobs.  Since there's no LOS check on that, it leads to lords spamming heal over and over again to heal guards on the outside of the keep.
This changes the three lord heal spells to be self targeted instead.
=> Make Lord heal self-only

GameServer/keeps/Gameobjects/Guards/Stealther.cs
Stealth guards weren't stealthing.
=> Keep Stealth Guards Being Stealthy

GameServer/ai/brain/ControlledNpcBrain.cs, GameServer/ai/brain/StandardMobBrain.cs
Added a few more buff types that mobs and pets weren't checking for.
LivingHasEffect() was checking for both matching spell effect group and spell type, which is incorrect.  Offensive procs should stack, as should pulsed damage adds and damage buffs.  Spell effect group exists specifically to allow those combinations, so it's odd to not use it exclusively.
=> Fix Stacking Buffs, added more buff types

GameServer/keeps/Managers/Spell Manager.cs
Removes the uninterruptible tag from PvE lords' self heal.  Lords should be soloable in PvE, and an uninterruptible self heal makes that impossible.
=>  Make PvE Lord heals interruptible

GameServer/ai/brain/Guards/KeepGuardBrain.cs
Causes archers to drop aggro on targets that move outside their aggro range.  This prevents them from continuing to draw and fire arrows each Think(), leading to all the arrows striking the target at once when they're back in range.
=> Fix archer bug

GameServer/gameobjects/GamePlayer.cs
Ensure player starts with full Health/Mana/Endurance when level >1 in server properties using played time <1.
=> Start Level >1 Health/Mana/Endurance fix

GameServer/gameobjects/GamePlayer.cs, GameServer/serverproperty/ServerProperties.cs
Added server properties to replace hard coded values determining at which level characters start to lose xp on death, lose con on death, and suffer ress sickness on death.
I did it to set those values at level 51 and not have them happen at all, but figured some folks might want to still have such things at high levels.
=> Added con loss, xp loss, ress sickness on death server properties

GameServer/gameobjects/GameNPC.cs, GameServer/gameobjects/GamePet.cs, GameServer/propertycalc/CriticalArcheryHitChanceCalculator.cs, GameServer/propertycalc/CriticalMeleeHitChanceCalculator.cs, GameServer/propertycalc/CriticalSpellHitChanceCalculator.cs, GameServer/serverproperty/ServerProperties.cs
Spells cast by necro pets weren't getting the benefit of the necromancer's Wild Power RAs.  NPCs were using the CriticalMeleeHitChanceCalculator for ranged attacks, leading to a higher crit chance, and to BD archer pets getting the benefits of Wild Minion on their ranged attacks.  This remedies that.
It also adds a new server property, EXPAND_WILD_MINION, which expands the Wild Minion RA to increase the crit chance of pet spells and ranged attacks.
=> Fix critical property calculators

GameServer/keeps/AbstractGameKeep.cs, GameServer/keeps/Managers/Template Manager.cs, GameServer/serverproperty/ServerProperties.cs
Keep guards were hard coded to respawn between 5 and 25 minutes.  This replaces that with two server properties: GUARD_RESPAWN and GUARD_RESPAWN_VARIANCE.
This is something I wanted for PvE servers, since keep lords pull the entire keep when aggro'd, so having guards respawn before you get to the lord makes keeps nearly impossible.  I figured it was better to expose this for people to be able to tweak it rather than hard code a different value for PvE/PvP servers.
=> Replaced hard coded keep guard respawn time with server properties

GameServer/packets/Client/168/DoorRequestHandler.cs
Door requests were only checking for PvP and Normal server types, so players couldn't open any doors on any other server type.  All server types are now being handled correctly.
Changed a few redundant if statements to else while I was there.
=> Added door support for all server types

GameServer/GameServer.csproj, GameServer/gameobjects/CustomNPC/Teleporters/AllRealmsTeleporter.cs
Adds a DOL.GS.AllRealmsTeleporter class type, which gives access to all three realms' teleport locations for PvE and PvP servers.
=> Adds all realm teleporter

GameServer/spells/SpellHandler.cs
Only damaging spells and spells that were resisted were calling OnAttackedByEnemy().  As a result other spell types could be used to pull and bypass bring a friend checks.
=> Hostile Effects trigger GameNPC.OnAttackedByEnemy()

GameServer/commands/playercommands/train.cs, GameServer/packets/Client/168/PlayerTrainRequestHandler.cs, GameServer/serverproperty/ServerProperties.cs
I really like Phoenix letting people use the /train command to train anywhere in the world rather than having to run back to their trainer, so I added that functionality.  Since it's not livelike, it's disabled by default and has to be enabled by the allow_train_anywhere server property.
=> Added allow_train_anywhere functionality

GameServer/ai/brain/Necromancer/NecromancerPetBrain.cs, GameServer/gameobjects/Necromancer/NecromancerPet.cs
Necro pet spellcasting wasn't properly being interrupted.  I've added code to use OnAttackedByEnemy() and MakeAttack() to properly interrupt pet spellcasting.
One consequence was that instant spells in the queue behind spells currently being cast were being removed from the queue, so instant cast spells now bypass the queue entirely.
=> Necro pet spellcasting now interrupted when they attack or are attacked

GameServer/ai/brain/StandardMobBrain.cs, GameServer/gameutils/BattleGroup.cs, GameServer/serverproperty/ServerProperties.cs
Live almost always sends BAF mobs after the player who pulled, so I added a server property to choose whether mobs go after random players or after the player who pulled them.
I also expanded the code to look for battlegroups so that it counts and sends mobs after all the players in a raid rather than just the players in the pulling group.  Since BGs can be up to 64 players by default, I tried to make the code as efficient as possible.
During testing, I found that BattleGroup.GetPlayersInTheBattleGroup() always returned an empty array, so I fixed it.
=> Added BAF_MOBS_ATTACK_RANDOM_PLAYERS server property, expanded to check battlegroups

GameServer/spells/EnduranceHealSpellHandler.cs, GameServer/spells/PowerHealSpellHandler.cs
There was some redundant code copy/pasted over from heal spells that I removed.
I moved the percent calculation so that AE spells now restore a percentage of the target's end/mana rather than being based on the caster's end/mana.
This was a happy coincidence of fiddling with pet scaling code, and I didn't end up needing to add pet scaling here anyway.  :-)
=> Fix power end heal spells

GameServer/gameobjects/GamePet.cs
I noticed when testing BAF code that pets will cast buffs on groupmates, but will only strip their buffs from their owner when they die.  They now strip their buffs from all group members when they die, or just the owner if they aren't part of a group.
=> Pets strip buffs from groups when they die

GameServer/gameobjects/Necromancer/NecromancerPet.cs
GetModified() was basing max health on base rather than modified con, leading to necro pets not being increased by con buffs like other pets.
=> Con buffs on necro pets now increase max health

GameServer/gameobjects/Necromancer/NecromancerPet.cs, GameServer/serverproperty/ServerProperties.cs
This is the same thing I did with mob, pet, and keep guard stats.  Greater necroservants have different stat calculations, so I had to use a second set of server properties for them.
=> Exposed necro pet stats via server properties

GameServer/gameobjects/GameNPC.cs, GameServer/gameobjects/GamePet.cs, GameServer/spells/HealSpellHandler.cs, GameServer/spells/SpellHandler.cs, GameServer/spells/SummonSpellHandler.cs, GameServer/styles/StyleProcessor.cs
Pet spell scaling code is now significantly better.  Rather than scaling spells as pet cast them, spells are scaled as they're added to the pet.  Subspells and style effects are scaled on the fly by SpellHandler and StyleProcessor as they aren't stored on the pet.
There is no longer any need for spell scaling in specific spell handlers.
A fringe benefit is that spells that necromancer pets cast automatically and their style effects will be scaled, but spells cast by the necromancer won't.
=> Improved pet spell scaling

GameServer/gameobjects/CustomNPC/GameBoatStableMaster.cs, GameServer/gameobjects/CustomNPC/GameStableMaster.cs
On live, when you buy a ticket, it's immediately given to the merchant to start the trip.  I overloaded OnPlayerBuy() to add that feature.
It checks for "ticket to" in the ticket name, but also checks for "ticket" as the description.  This should make it function for English servers immediately, while giving non-English servers a way to make it work.
=> Tickets are now automatically given to merchant when bought

GameServer/gameobjects/GameNPC.cs, GameServer/gameobjects/GamePet.cs
When I tested pets on live, they use positional styles every single time, so I've updated style sorting and selection to do so as well.
I moved defensive styles before the chance to style check, which should make those styles more visible since most NPCs have very low block/evade/parry chances.
A fringe benefit of more granular sorts is random style selection.  NPCs can be given multiple styles requiring the same position, and the NPC will randomly choose from them rather than only using the first one in the list e.g. an NPC could have Pincer and Decaying Rage side styles and use both of them.
I also noticed that the SortSpells() method was clearing the instant harmful spell list twice and not clearing the miscellaneous spell list, so I remedied that.  It doesn't matter right now, but it …
=> Improved NPC style sorting and selection

GameServer/commands/gmcommands/mob.cs
/mob info now lets you see both a mob's buffed and unbuffed stats.  Especially useful when looking at pets that have a self-buff spell.
=> /mob info now shows base and modified stats

GameServer/ai/brain/StandardMobBrain.cs, GameServer/serverproperty/ServerProperties.cs
Added several new server properties to expose BAF functionality for BGs.  Changed constants to virtual accessors so they can be properly overridden, and added an accessor to specify range for the player IsWithinRadius() check.
By default, BGs are ignored, number of mobs added is based on number of nearby group members, and adds attack random nearby members of the puller's group.
I tested this exhaustively and found a few bugs and possible exploits.  Code now checks for duplicates, players who are in both the group and the BG so they aren't counted twice, but only when absolutely necessary and as efficiently as possible.
=> Fixed BringFriends() bugs/exploit, added more server properties

GameServer/gameobjects/GamePet.cs
GamePet.GetModifiedSpecLevel() was originally copy/pasted out of BDPet code, so I suspect it written to only check for styles that BD pets use.  Styles tied to other weapon types would return 0, which removes all style damage from Style.GrowthRate.
I haven't found any situation in which the owners spec returns non zero, but I think it's safer to leave it in than risk breaking something I can't see.
=> Fixed GetModifiedSpecLevel() returning 0

GameServer/gameobjects/Bonedancer/CommanderPet.cs, GameServer/gameobjects/CharacterClasses/CharacterClassBase.cs, GameServer/gameobjects/GamePet.cs, GameServer/spells/Spell.cs, GameServer/spells/SpellHandler.cs
StripOwnerBuffs() had a potential exploit; a player could join a group, be buffed by a groupmate's pet, leave the group, and not have buffs cast by the pet stripped.
Pets now track which targets they've buffed via AddBuffedTarget(GameLiving).  StripOwnerBuffs(owner) has been changed to StripBuffs(), since the owner is no longer needed.
I added a few other things along the way.  Spells now have IsHelpful and IsBuff properties, IsHealing and IsHarmful are now more efficient, and SpellHandler.HasPositiveEffect now calls Spell.IsHelpful rather than duplicating code.
=> Updated pet buff stripping code

GameServer/ai/brain/ControlledNpcBrain.cs, GameServer/ai/brain/StandardMobBrain.cs, GameServer/gameobjects/Bonedancer/CommanderPet.cs, GameServer/gameobjects/GameLiving.cs, GameServer/gameobjects/GameNPC.cs, GameServer/gameobjects/GamePet.cs, GameServer/gameobjects/GamePlayer.cs, GameServer/gameobjects/Necromancer/NecromancerPet.cs, GameServer/spells/Spell.cs, GameServer/spells/SpellHandler.cs, GameServer/spells/SummonSpellHandler.cs, GameServer/styles/StyleProcessor.cs
This is a significant overhaul of pet AI, which took me much further down the rabbit hole than I expected.  Since pet AI is far simpler and easier to test than mobs, I've tried to change as little of StandardMobBrain as possible.  I plan to work on that next, but it will be a separate PR.
Changes:
Pets now use sorted spell lists rather than stepping through all of their spells each tick.
Pets will now stop melee attacking to cast offensive and defensive spells so long as they aren't being interrupted.
Pets now use instant spells when in melee and in the middle of casting other spells.
Pets that can heal now check for in two passes to prioritize healing badly injured targets, and now heal their owner before themselves.
Added more robust spell checking to catch invalid spell casts earlier …
=> Improved pet spellcasting AI

GameServerScripts/quests/Albion/epic/Defenders50.cs, GameServerScripts/quests/Hibernia/epic/Focus50.cs, GameServerScripts/quests/Midgard/epic/Viking50.cs
Rather than allowing all classes to take the quest but not complete it, classes other than maulers can get and complete the quest while maulers can't start the quest.
=> Epic quests now works for non-mauler classes

DOLDatabase/Tables/Mob.cs, DOLDatabase/Tables/NpcTemplate.cs, GameServer/ai/brain/ControlledNpcBrain.cs, GameServer/commands/gmcommands/mob.cs, GameServer/gameobjects/Bonedancer/BDSubPet.cs, GameServer/gameobjects/CharacterClasses/CharacterClassBase.cs, GameServer/gameobjects/CharacterClasses/Midgard/CharacterClassBoneDancer.cs, GameServer/gameobjects/GameNPC.cs, GameServer/gameobjects/GameObject.cs, GameServer/gameobjects/GamePet.cs, GameServer/gameobjects/GamePlayer.cs, GameServer/gameobjects/Necromancer/NecromancerPet.cs, GameServer/gameutils/INpcTemplate.cs, GameServer/gameutils/NpcTemplate.cs, GameServer/quests/Tasks/CraftTask.cs, GameServer/serverproperty/ServerProperties.cs, GameServer/spells/Animist/BomberSpellHandler.cs, GameServer/spells/Animist/SummonAnimistFnF.cs, GameServer/spells/Bonedancer/SummonMinionHandler.cs, GameServer/spells/Necromancer/SummonNecromancerPet.cs, GameServer/spells/SpellHandler.cs, GameServer/spells/SummonIllusionBlade.cs, GameServer/spells/SummonSpellHandler.cs, GameServer/world/ZonePointEffects.cs
This is another relatively simple sounding thing that led to a lot of changes.
Pets now level up with their owners if the PET_LEVELS_WITH_OWNER server property is true, default is false.  Pet spell scaling was revisited to have spells re-scaled when the pets level changes.
BD subpet spell scaling being capped by spec is now enabled by the PET_CAP_BD_MINION_SPELL_SCALING_BY_SPEC server property, disabled by default.  BDSubPet overrides pet scaling and sorting functions to move BDSubpet specific code out of GamePet.
Code to calculate pet level was moved from SummonSpellHandler to GamePet.  GamePet now stores the damage and value from the spell that summons them to allow their level to be changed on the fly.
Fixed a bug with Necro pet spellcasting interruptions only happening when a second …
=> Optional: Pets level with owner

GameServer/gameobjects/GameNPC.cs, GameServer/serverproperty/ServerProperties.cs
Guards/mobs/pets lose their chance to block when using a 2H weapon, but do not get any bonus damage to make up for it.  This adds the lost block chance as a percentage of damage to compensate.  Server properties allow it to be turned on or off for guards, mobs, and pets separately.
Keep lords & mission masters get a 15% block chance, fighters get 10%, and healers get 5%, so this will definitely have an impact on guards but not a game breaking one, so 2H damage is enabled by default for keep guards.
There are 12 mob npcTemplates in Eve that give a block chance and a 2H weapon, and they paradoxically only have 2H weapons so they can't ever block anyway.  Since they don't lose anything it doesn't make sense to give them bonus damage, so mob 2H damage is disabled by default.
I tested BD pets …
=> Added 2H bonus for guards/mobs/pets

GameServer/ai/brain/StandardMobBrain.cs, GameServer/gameobjects/GameNPC.cs
Previously, each think() cycle set a new random location to roam to, leading to mobs erratically wandering short distances from their spawn regardless of their roaming range.
Mobs now walk all the way to a chosen roaming destination before picking a new one, so mobs with high roaming ranges will wander significantly further from their spawn point.
Also simplified CalcRandomWalkTarget significantly, removing an unused angle calculation and redundant radius calculation.
Fringe benefit: Overhead from roaming mobs should be a lot lower.
=> Reduced roam frequency, longer roam distances

GameServerScripts/quests/Albion/epic/Academy50.cs, GameServerScripts/quests/Albion/epic/Church50.cs, GameServerScripts/quests/Albion/epic/Defenders50.cs, GameServerScripts/quests/Albion/epic/Shadows50.cs, GameServerScripts/quests/Hibernia/epic/Essence50.cs, GameServerScripts/quests/Hibernia/epic/Focus50.cs, GameServerScripts/quests/Hibernia/epic/Harmony50.cs, GameServerScripts/quests/Midgard/epic/MidgardRogue50.cs, GameServerScripts/quests/Midgard/epic/Mystic50.cs, GameServerScripts/quests/Midgard/epic/Seer50.cs, GameServerScripts/quests/Midgard/epic/Viking50.cs
Some quest mob names are reused (Elizabeth), and others are duplicated in strange places in Eve.  This made some quests impossible.  Quests now check for name, region, and x/y coordinates to make sure the correct NPC is being selected rather than assuming the first one in the list is the one we want.
Tweaked a few things as well, making coordinates match Eve and correcting incorrect quest text.
=> Fix Quest Mob Selection

GameServer/gameobjects/GameNPC.cs
2H damage was being set rather than multiplied, leading to damage being reduced to ~1.
=> Fix 2H damage bonus

GameServer/gameobjects/CharacterClasses/Midgard/CharacterClassBoneDancer.cs
When pets level with owner, and BD pet spells are capped based on spec, and the current pet doesn't have any subpets, a null exception would be thrown which leads to the player's spell list not being updated.
=> Fix null exception for BD pets without subpets

GameServer/gameutils/Atlantis/InventoryArtifact.cs
Fixes a bug where all stats of an artifact (version) are reset globally when someone turns in an artifact quest (for this version). Bug was caused by altering the global cached ItemTemplate instead of a copy.
=> Fix ArtifactTurnInQuest breaking all Artifacts

DOLDatabase/ObjectDatabase.cs
Correctly return null when no item is found
=> Fix ObjectDatabase.SelectObject

GameServer/ai/brain/StandardMobBrain.cs
This small change to StandardMobBrain.CheckPlayerAggro() ensures that the Z-axis is respected in dungeons analogue to how it is done in CheckNpcAggro().
Mobs in dungeons will no longer aggro on players in rooms far above or below them.
In Darkness falls in particular this would cause body pulls of high level mobs appearing seemingly out of thin air or coming out of walls.
=> Bug Fix: Mobs adding through floors/ceilings/coming out of walls

DOLDatabase/WhereExpression.cs, GameServer/managers/playermanager/FriendsManager.cs, GameServer/packets/Server/PacketLib1104.cs, Tests/IntegrationTests/Database/DatabaseTests.cs, Tests/UnitTests/UT_WhereExpression.cs
Add `DB.Column.IsIn` operator which transform to sql `IN`, it's a bit more complex than other operators but it can save many SQL queries if it's used correctly. There are 2 usages of this optimization, we can find many more in the code but it's not obvious.
Also, I added a small unit test for `FindObjectsByKey`.
=> Whereexp isin

GameServer/commands/playercommands/time.cs, GameServer/world/WorldMgr.cs
This fixes the glitches we randomly have in-game when server decides to send a time update packet to the client to resynchronize the clocks. When that happens we used to suddenly see daytime changes.
This also allows the clock with /time to fully count towards 23:59 and not rollback halfway around ~20:00.
=> Fix day constant and avoid in-game time glitches

GameServer/gameutils/SkillBase.cs, GameServer/packets/Client/168/DetailDisplayHandler.cs, GameServer/packets/Server/PacketLib1110.cs, GameServer/packets/Server/PacketLib1124.cs, GameServer/spells/ISpellHandler.cs, GameServer/spells/SpellHandler.cs
I think we should move the spell level in spell's table instead of having it in the spell line. I don't think a same spell is used in different spell lines with a different level and even if it's the case, the spell can be duplicated.
=> fix spell level in delve tooltip/popup

GameServer/gameobjects/GameNPC.cs
- Now Pets will follow players in relation with their speed
- In order to make this work, some adaptations were necessary on BomberBrains while in combat in order to hit their target normally (without beeing stuck)
=> Fix Pets following player erratically

GameServer/gameutils/GamePlayerInventory.cs, GameServer/packets/Client/168/PlayerMoveItemRequestHandler.cs
Here we consider items that are Item_Type = LeftHandWeapon and Hand = 2.
When moved from any slot onto the player paper doll, they were given a toSlot = LeftHand.
This would work for characters with ability to wield left handed weapons.
But if the character does not have this ability, the object would simply tell "This can't go there.".
The proper solution is to always put "Usable in left hand" weapons in the right hand weapon.
I verified on live and this is the expected behaviour.
If you want to put a weapon in the left slot, you have to tell it explicitely by putting it on the left slot and not on the paper doll.
=> Automatically equip left-handed items

GameServer/gameobjects/GameLiving.cs
If GM use viewloot, need remove the attacker from the xpGainers, else if he deco/reco and redo the action, he appears twice in the list and the bug does happen
Cherry-picked from @Lord-Seithenin (Dawn-of-Light/DOLSharp#315)
=> Fix bug when loot items as GM:

DOLDatabase/SQLObjectDatabase.cs
The prepare statement is useful only if we re-use the prepared statement but in DOL, a new statement is created every time.
=> remove useless SQL prepare statement

DOLBase/Constants.cs, DOLBase/DOLBase.csproj, Net5/DOLBase/DOLBase.csproj
Daoc use Windows-1252 as text encoding which is the default encoding in .net 4.8 on windows but it's utf-8 for other platforms (and .net core).
=> fix text encoding

GameServer/gameutils/Skill/Delve/SongDelve.cs, GameServer/gameutils/Skill/Delve/SpellDelve.cs, GameServer/packets/Client/168/DetailDisplayHandler.cs
Retrieve the correct spell level to show in the tool tip.
This fix is simplier than the previous PR
=> Spell tooltip fix : Retrieve the correct spell level

GameServer/packets/Server/PacketLib1126.cs, GameServer/packets/Server/PacketLib1127.cs, GameServer/packets/Server/PacketLib168.cs, GameServer/packets/Server/PacketLib175.cs, GameServer/serverrules/IServerRules.cs
Fix character creation, which was previously not usable with other server rules than PvE/PvP
Fix realm switcher not being available after logging a char in and out
Fix a small calculation error in PacketLib1126 weapon damage calc
=> Fix character creation and realm switching in 1.126+

.github/workflows/create_release.yml, .github/workflows/test_runner.yml
Allow to check more easily which Nuget dependencies were used for the releases build.
=> Github Actions Build with more verbosity

.github/workflows/create_release.yml
Improves Release package Compatibility with Mono.
This will allows to release .NetFramework Linux based Docker Images using Release Build artifacts.
=> Add SQLite Binaries for Linux / OSX to Windows Release

GameServerScripts/GameServerScripts.csproj, Net5/DOLBase/DOLBase.csproj, Net5/DOLConfig/DOLConfig.csproj, Net5/DOLDatabase/DOLDatabase.csproj, Net5/DOLServer/DOLServer.csproj, Net5/GameServer/GameServer.csproj, Net5/GameServerScripts/GameServerScripts.csproj, Net5/Tests/Tests.csproj
Remove unused redundant libraries
Remove satellite language resources (from Microsoft.CodeAnalysis)
Remove precompiled GameServerScripts (on .Net Framework as well)
=> Cleanup .Net5 build output

GameServer/commands/playercommands/yell.cs
Yell heading does not depend on target heading but only on current player's heading.
Also used this opportunity to improve the code using `IsSpammingCommand`
=> Fix yell angle

GameServer/serverproperty/ServerProperties.cs, GameServer/spells/SpellHandler.cs
At the moment the spell handler only performs 3 checks. This is okay for most casts which are shorter than 5 seconds total.
For other spells which are longer, this will be a problem since a lot of things can happen in the meantime of each check.
Let’s take the example of a cast which lasts 15 seconds: `time = 15000`.
`step1 = time / 3` i.e. step 1 = 5000 but with the current values for the server properties step1 is limited to 1500 so step1 = 1500.
Same thing for step3 = 1500.
It follows `step2 = time - step1 - step3` so step2 = 12000.
What this means is the following: CheckAfterCast is executed after 1500ms
CheckDuringCast is executed 12000ms later
CheckEndCast executed 1500ms after.
A lot of things can happen between AfterCast and DuringCast in a 12000ms interval. It would be nice to be …
=> Improve SpellHandler to perform repeated checks "during" cast for long running spells

DOLBase/Network/PacketOut.cs, GameServer/packets/Server/PacketLib1125.cs, GameServer/packets/Server/PacketLib1126.cs
A fix with big changes, it fixes the character overview for 1.125+.
The WriteByte(0) seems odd but it was what I got from official server (with 1.127e).
After a small time with disassembled game.dll, I retrieved some string limits.
=> fix packet: writing pascal string off by one + max length

GameServer/gameobjects/GameInventoryItem.cs
An instrument does not have DPS or SPD, Effective Damage, etc...
For instruments, DPS_AF is used to indicate what kind of instrument the object is (drum, lute, flute, harp).
Currently, delving instruments show "0.1 Base DPS / 0.1 Clamped DPS / 0.1 Effective DPS" etc...
With this change I remove `DelveWeaponStats` which is not necessary for instruments.
=> Do not delve the 'weapon' stats of an instrument

GameServer/ai/brain/Guards/Lord.cs, GameServer/keeps/Gameobjects/Guards/GameKeepGuard.cs, GameServer/serverproperty/ServerProperties.cs
Possibility to remove the Keep Lord to heal itself 
0=no self heal
1=self heal (which is the default)
On low level keeps (battlegrounds), the keep lord seems impossible to kill with a little group if he has a non-interruptible self heal
=> Adjustment on keep lord auto-heal for low level BG

GameServer/packets/Client/168/LoginRequestHandler.cs
The dictionary is currently a member of the LoginRequestHandler class, which means that there is one Dictionary per account, therefore there is only ever one item added to it and one lock held! This defeats the purpose of having a dictionary at all for the login process.
Changing the dictionary as static instead makes it relevant to actually acquire server-wide locks.
=> Use a static dictionary to hold the locks for all logins

GameServer/keeps/GameKeepComponent.cs
In case of usage of the /keep addbanner realm command, the GameKeepBanner are now taken into account for the battleground keeps :)
=> Battleground : addition of GameKeepBanner in the battleground keeps

GameServer/gameobjects/InventoryItem/GameInventorySiegeRam.cs
This new class will require 4 new itemtemplates in the DB corresponding to each kind of siege ram and must be linked to DOL.GS.GameInventorySiegeRam via the ClassType field
This PR will be linked to another PR on the db-public repo to complete this enhancement
=> SiegeRam : new InventoryItem class to create a siege ram

GameServer/styles/StyleProcessor.cs
Weapons below 1.5 DPS do zero style damage instead
=> Fix weapons with 0 DPS doing infinite style damage

GameServer/commands/gmcommands/keepguard.cs
Patrol guards wouldn't use the created path previously
=> Fix /keepguard path command

GameServer/keeps/Gameobjects/GameKeepDoor.cs
As the side doors have some "air" space between external and internal part, the size of the jump need to be extended to 175
=> KeepDoor : transversal keep door need a larger size

GameServer/serverproperty/ServerProperties.cs
As the old keep skin is giving some blank texture, proposal is to use the new keep skin by default which is better supported.
=> KeepSkin : use new keep skin by default

GameServer/Finance/Currency.cs, GameServer/Finance/Wallet.cs, GameServer/gameobjects/GameMerchant.cs, GameServer/gameutils/MerchantCatalog.cs, GameServer/packets/Server/PacketLib168.cs
Merchants accept also ItemTemplates that have no ClassType but same Id_nb as ItemCurrency.id
Separate ToText() and ID
Determine ToText() by ItemTemplate.Name of Item.Id_nb == ItemCurrency.id 
Fix wrong display of Copper MerchantCatalogPages that follow other ones
=> Accept currency item if ID is the same

GameServer/gameobjects/GameInventoryObject.cs
Every item added to the player's inventory needs to be a `GameInventoryItem` type. There exists a condition in `GameInventoryObject`s which allow to exchange two items from a vault, during which the item received loses its type and uses InventoryItem instead.
A player could exploit this behaviour to prevent items from losing condition (for example). Indeed once turned into bare `InventoryItem`s [this code](https://github.com/Dawn-of-Light/DOLSharp/blob/master/GameServer/gameobjects/GameInventoryItem.cs#L285) is no longer called.
Note there are probably other places in the code where we are pushing an `InventoryItem` instead of a `GameInventoryItem` and we forget to `GameInventoryItem.Create`.
This begs some questions:
1. Why do the interface `IGameInventory` and all derivatives not accept …
=> Create a GameInventoryItem when interacting with a GameInventoryObject

GameServer/spells/SummonSpellHandler.cs
Remove Brain injection via NPCTemplate.ClassType, because it is beyond the intended behavior for NPCTemplate.ClassType
=> Fix Traitor's Dagger Vampiiric Mist proc

GameServer/gameobjects/GameNPC.cs
Caused by a mismatch of Flags property and underlying m_flags member
Always use property except inside the Flags property itself and constructor
=> Fix FrontierHastener sometimes attacking

DOLDatabase/WhereClause.cs
Statement with "IN ()" not valid in MySQL (but SQLite)
=> Hotfix: Server not starting

GameServer/ai/brain/ControlledNpcBrain.cs, GameServer/ai/brain/StandardMobBrain.cs, GameServer/effects/ProtectEffect.cs
A while back, I gave custom pets the protect ability to apply to their owners, but it never worked properly as ProtectEffect assumed both the source and target of protect effects were players.  This remedies that by allowing the effect to be applied by and on GameLivings.
The ability handler already limits players to applying the effect to other players in their group, so vanilla behaviour hasn't changed, and the only other possible application currently is custom pets protecting their owners.  That said, I tried to future proof it so that other contexts are possible.  Somebody could create a group vs group fight between NPCs, and have tank NPCs protect healing NPCs, for example.
While I was there, I cleaned up the code and addressed compiler warnings and recommendations.
=> Allow NPC Protect Effect

GameServer/packets/Server/PacketLib168.cs
Previously Shift+Rightclick menus weren't shown
=> Fix Housing Menus for clients <1.125
