- GameServer/GameServerConfiguration.cs
- UnitTests/GameServer/gameutils/DatabaseTest.cs
- UnitTests/GameServer/gameutils/GameLivingInventoryTest.cs
- UnitTests/GameServer/gameutils/InventoryTest.cs
- UnitTests/GameServer/gameutils/LanguageTest.cs
- UnitTests/GameServer/gameutils/LootMgrTest.cs
- UnitTests/GameServer/gameutils/RegionTest.cs
- UnitTests/GameServer/gameutils/ServerTest.cs
- UnitTests/GameServer/gameutils/Train1105.cs
- UnitTests/GameServer/gameutils/ZoneTest.cs
- UnitTests/GameServer/quests/KillTaskTest.cs
- UnitTests/GameServer/quests/MoneyTaskTest.cs
- UnitTests/GameServer/world/RegionOidAllocation.cs
- UnitTests/Server.cs
- UnitTests/SetUpTests.cs
- UnitTests/UPnP.cs
- UnitTests/UnitTests.csproj
- appveyor.yml
Restore Unit Test with Nunit Framework.
Allowing Continuous Integration with Server Startup Test.
> Nunit Test restored

- .travis.yml
- README.md
- UnitTests/UnitTests.csproj
Added Travis YML build file.
Updated Test project to include "Unix" Like post event build command.
Updated Readme to reflect the Travis CI status.
> Integrating Travis CI for Mono Build Test and Nunit Tests

- DOLDatabase/CustomParam.cs
- DOLDatabase/DOLDatabase.csproj
- DOLDatabase/IObjectDatabase.cs
- DOLDatabase/Tables/Account.cs
- DOLDatabase/Tables/DOLCharacters.cs
- DOLDatabase/Tables/DOLCharactersBackup.cs
- DOLDatabase/Tables/Spell.cs
- GameServer/GameClient.cs
- GameServer/gameutils/Params/CustomParamsExtensions.cs
- GameServer/gameutils/Params/ICustomParamsValuable.cs
- GameServer/packets/Client/168/CharacterCreateRequestHandler.cs
- GameServer/spells/Spell.cs
- UnitTests/Database/CustomParamsTest.cs
- UnitTests/Database/DatabaseSetUp.cs
- UnitTests/Database/DatabaseTests.cs
- UnitTests/Database/TestDataObjects.cs
- UnitTests/SetUpTests.cs
- UnitTests/UnitTests.csproj
Add Pre-Implementation for Custom Params on Account / Characters
This will allow external script to store key/value pairs for later use without using a new scripted table every time.
Added Some Basic DOL Database Unit Tests to prevent regression for future improvements...
> Custom Params and Database Unit Tests

- DOLDatabase/ObjectDatabase.cs
- GameServer/gameutils/Params/CustomParamsExtensions.cs
Quick Fix for Spell initialization during server startup.
> Params Extension Init From Collection not accepting null collections

- GameServer/GameServer.cs
- GameServer/GameServer.csproj
- GameServer/commands/gmcommands/mob.cs
- GameServer/gameobjects/GameNPC.cs
- GameServer/gameobjects/GamePet.cs
- GameServer/managers/MobAmbientBehaviourManager.cs
- GameServer/managers/NpcManager.cs
Only handling MobXAmbientBehaviour for now to speed up GameServer startup.
> NPC Manager for handling Static Mob/Npc Data

- GameServer/GameServer.cs
- GameServer/GameServer.csproj
- GameServer/commands/playercommands/lastname.cs
- GameServer/config/invalidnames.txt
- GameServer/managers/npcmanager/MobAmbientBehaviourManager.cs
- GameServer/managers/npcmanager/NpcManager.cs
- GameServer/managers/playermanager/InvalidNamesManager.cs
- GameServer/managers/playermanager/PlayerManager.cs
- GameServer/packets/Client/168/BadNameCheckRequestHandler.cs
- GameServer/packets/Client/168/DuplicateNameCheckRequestHandler.cs
- UnitTests/GameServer/InvalidNamesStartupTest.cs
- UnitTests/Managers/InvalidNamesManagerTest.cs
- UnitTests/UnitTests.csproj
Include Default invalidnames.txt ressources based on game.dll hardcoded censoring.
Move NpcManager to its own folder.
Writing some unit tests for the Invalid Name Manager.
> Update: Add Player Manager Handling Invalid Names.

- .travis.yml
Newer version of Nunit Console seems to fail with Project...
> Travis Nunit Console Version set Explicitly

- GameServer/GameClient.cs
- GameServer/GameServer.csproj
- GameServer/packets/Server/PacketLib1118.cs
- GameServer/packets/Server/PacketLib1119.cs
- GameServer/packets/Server/PacketLib1120.cs
- GameServer/packets/Server/PacketLib1121.cs
- GameServer/packets/Server/PacketLib1122.cs
- GameServer/packets/Server/PacketLib1123.cs
- GameServer/packets/Server/PacketLib1124.cs
- GameServer/packets/Server/PacketLib1125.cs
Current 1.121 and up to future 1.125
> Update: Add PacketLib Stub Classes for Client Later Versions

- DOLDatabase/Handlers/MySQLObjectDatabase.cs
- DOLDatabase/Handlers/SQLiteObjectDatabase.cs
- DOLDatabaseTests/RegisterTableTests.cs
- DOLDatabaseTests/TestTableObjects.cs
Enforce Default Values for Table Column when migrating from Null to Non-Null value in case of existing Null Records.
> Fix Database Migration Null to Not Null

- GameServer/gameutils/Atlantis/InventoryArtifact.cs
Try to retrieve a non-shared (precache) DataObject when creating InventoryArtefact Instance.
> Artefact Inventory Item Template Fix

- GameServer/gameutils/LootGeneratorChest.cs
- GameServer/realmabilities/handlers/AmelioratingMelodiesAbility.cs
- GameServer/serverproperty/ServerProperties.cs
Live like small and large chest generator. Drop chance and multiplier can be set in server properties
fix to AM , correct value for level 4 of the realm ability
> bug fix and lootgen

- GameServer/spells/AblativeArmorSpellHandler.cs
- GameServer/spells/DamageAddAndShield.cs
- GameServer/spells/ProcSpellHandler.cs
- GameServer/spells/PropertyChangingSpell.cs
- GameServer/spells/ResistDebuff.cs
- GameServer/spells/SingleStatBuff.cs
- GameServer/spells/SingleStatDebuff.cs
- GameServer/spells/SpeedEnhancementSpellHandler.cs
- GameServer/spells/WaterBreathingSpellHandler.cs
Fix various interactions between spell duration and Resurrection sickness, Mastery of Concentration, and Spec level.
> Various fixes to durations and effectiveness.

- GameServer/commands/gmcommands/mob.cs
Adds code so /mob brain can create a brain instance from GameServerScripts as well as Gameserver assemblies. Removed some redundant code , and added error message with some hints.
> Adds some new code to /mob brain

- GameServer/GameServer.csproj
Someone asked me how to use this today, and i realised i forgot to include my chest generator to compile list so it can actually be used.
> add previously commited lootgen to compile list

- GameServer/gameutils/MovementMgr.cs
makes LoadPath() thread safe to prevent concurrent cache filling and crashing server on startup. Code originally suggested by Leodagan in this thead here [http://www.dolserver.net/viewtopic.php?f=6&t=22910](url)
> fix movementmgr startup crash

- GameServerScripts/customnpc/SparringDummy.cs
A dummy mob for testing purposes. Can be set to idle, or to fight back. Can have level, block, parry, evade adjusted to some set values.
> Sparring dummy

- GameServer/ai/brain/ControlledNpcBrain.cs
- GameServer/spells/ProcSpellHandler.cs
Fix bug where pet would not "stay"
Add call to CheckAbilities() so pet abilities are actually loaded. ie Spiritmaster pet intercept.
Add support for multiple offensive procs. ie spiritmaster pets.
> controlledNPC bugfixes

- GameServer/quests/Tasks/AbstractTask.cs
"I have no tasks for you at the moment. Come back sometime later, perhaps then you can help **we** with something."
Should read 
"I have no tasks for you at the moment. Come back sometime later, perhaps then you can help **me** with something."
> Grammar Correction in AbstractTask

- GameServer/packets/Server/PacketLib194.cs
- GameServer/quests/QuestsMgr/DataQuest.cs
Sends money reward and experience reward to the quest popup window.
> Dataquest 'reward' quest

- GameServer/commands/playercommands/guild.cs
**guild.cs in current SVN is in ANSI encoding not UTF-8 it also doesn't use the tab spacing so this PR looks odd. I am not sure how to correct this issue with formatting sadly.**
Hi all, a rework on the /gc form.
To form a guild, you must first form a full party of eight players, none of whom can already be guided. The person who is going to be the guild leader must visit the Guild Registrar NPC, found in the major cities of your realm. Each person must be in the same zone as the Guild Registrar. The group leader must select the Guild Registrar and type /gc form. Note that your guild's name must be unique. You cannot use a guild name that is already in use on your server. It costs one gold piece to start a guild. The money is deducted from the pocket of the character speaking to the Guild …
> Correct Guild Form Behaviour

- GameServer/gameobjects/CustomNPC/DreadedSealCollector.cs
- GameServer/gameutils/LootGeneratorDreadedSeals.cs
- GameServer/serverproperty/ServerProperties.cs
Added a loot generator and NPC object to drop and collect dreaded seals.  Added four new server properties to allow drop rates to be adjusted.
> Dreaded seals

- GameServer/gameobjects/GamePlayer.cs
- GameServer/language/DE/Ability.txt
- GameServer/language/EN/Ability.txt
- GameServer/language/FR/Ability.txt
- GameServer/skillhandler/CamouflageSpecHandler.cs
Changes to camouflage ability to reflect live-like mechanics and reuse timer.
Some translations added.
> Camouflage change to live-like

- GameServer/gameutils/DoorMgr.cs
- GameServer/keeps/KeepManager.cs
- GameServer/managers/npcmanager/MobAmbientBehaviourManager.cs
Load keeps faster by pooling their load.
Quit doing a db call per mob loading to get ambient texts.
> Speed up server start time

- GameServer/ai/brain/StandardMobBrain.cs
AddToAggroList() made the same mistake I did; checking for GamePet object rather than checking the brain.  This fixes both my and AddToAggroList's error, and also changes NaturalAggro to CheckLOS to make it self documenting.
> Fixed LOS checks for pets and charmed mobs

- GameServer/spells/SpellHandler.cs
Also fixed a few spell types that weren't properly in lowercase, causing them to not be scaled.
> Added a few more spell types to be scaled

- GameServer/gameobjects/GameDoor.cs
- GameServerScripts/dbupdater/insert/Regions.xml
Also cleaned up formatting because I'm weird that way
> Open mile gates on PVE and PVP servers

- GameServer/ai/brain/Guards/Lord.cs
- GameServer/gameobjects/GameNPC.cs
- GameServer/keeps/Gameobjects/Guards/GameKeepGuard.cs
- GameServer/keeps/Gameobjects/Guards/Hastener.cs
- GameServer/keeps/Gameobjects/Guards/Lord.cs
This replicates keep lord behaviour on Gaheris.
> New: Keep Lords call for help on PvE Servers

- GameServer/keeps/GameKeepComponent.cs
Gaheris only allows access to Cathal Valley, but I figure it we've got the content already there we may as well use it.
> Added: PvE BGs populate guards

- DOLDatabase/SQLObjectDatabase.cs
- GameServer/GameServer.cs
Parallel registering of db objects on server start.
> Speed up DB init

- GameServer/spells/BladeturnSpellHandler.cs
- GameServer/spells/ProcSpellHandler.cs
Adds some restored effects for bladeturn and offensive/defensive procs. (saves the effect when player exits and restores them when player logs back in)
> restored effects

- GameServer/packets/Server/PacketLib1124.cs
experimental: changed Server to Client packets in 1.124
> 1124 server packets

- GameServer/gameobjects/GameNPC.cs
- GameServer/spells/Spell.cs
Sorts spells into categorised lists, which will make AI modifications a lot easier and more efficient.
I cleaned up and added null checks to the style list code as well.
> Sort npc spells

- GameServer/commands/playercommands/emotes.cs
- GameServer/packets/Server/IPacketLib.cs
some emotes that got added a while back but missing from DOL. '/Cower' exists but i couldn't find the ID for now.
> new emotes

- GameServer/propertycalc/ArcheryRangePercentCalculator.cs
- GameServer/propertycalc/SpellRangePercentCalculator.cs
Change (int) rounding for debuff calculation to be applied after multiplication
> Fix debuff in SpellRangePercentCalculator

- GameServer/GameServer.csproj
The files were already there, they just needed to be added to the project.
> Added DreadedSealCollector.cs and LootGeneratorDreadedSeals.cs

- GameServer/gameutils/LootGeneratorDreadedSeals.cs
Number of seals dropped is now based on keep level
BGs only drop 1 seal
Keep lords and Agramon now properly drop sanguine rather than glowing seals
Removed code for dragons since they aren't in regions that will ever use this loot generator anyway
Mucked about with whitespace, with mixed results
> Now drops variable seals based on keep level

- GameServer/DolWebHook.cs
- GameServer/GameServer.cs
- GameServer/GameServer.csproj
- GameServer/serverproperty/ServerProperties.cs
Discord integration
This enables Discord using Webhook for your server. On the simplest format simply call
var hook = new DolWebHook(Properties.DISCORD_WEBHOOK_ID); hook.SendMessage(Your Message);
Enjoy
Loki
> Discord webhook integration

- GameServer/gameobjects/CustomNPC/Teleporters/AllRealmsTeleporter.cs
This changes the mixed text and link messages from the teleporter into minimalist menus with submenus.  Added a bunch of new teleport destinations including towns, dungeons, dragon zones, DF gates, Agramon, etc.
> Changed to minimalist submenus and added a lot of destinations

- GameServer/craft/AbstractCraftingSkill.cs
- GameServer/gameobjects/GamePlayer.cs
- GameServer/serverproperty/ServerProperties.cs
I got fed up maxing crafting skills in the DB by hand, so I added a server property to do it for me.  Default is false.
> Added server property to max crafting skills

- GameServer/GameServer.csproj
- GameServer/commands/gmcommands/ServerReboot.cs
Ability to reboot server for GM's that may not be in front of machine.
> Server reboot command for GM's.

- GameServer/commands/gmcommands/Player.cs
Something useful I've been using to test pets leveling up with their owners.
> Added /player levelup GM command

- GameServer/gameobjects/CustomNPC/Teleporters/AllRealmsTeleporter.cs
Copy/pasted GetTeleportLocation() from GameTeleporter and modified it to work outside of a realm specific teleporter.
Also changed DestinationRealm parameter to destRealm to avoid confusion with the GameTeleporter DestinationRealm accessor.
> Added GetTeleportLocation() to create dynamic teleport locations

- GameServer/GameClient.cs
- GameServer/managers/playermanager/FriendsManager.cs
- GameServer/serverproperty/ServerProperties.cs
Kick idle players after (x) minutes.
Server property KICK_IDLE_PLAYER_STATUS - enable/disable default disabled.
Server property KICK_IDLE_PLAYER_TIME - time in mintures
> Inactive player kick

- Dawn of Light.sln
- GameServer/commands/admincommands/Shutdown.cs
- GameServer/gameutils/ServerListUpdate.cs
- GameServer/serverproperty/ServerProperties.cs
- GameServerScripts/web/OnlineStatusUpdate.cs
Changed: SP Name changed - SERVERLISTUPDATE_ENABLED and AUTOSELECT_CASTER, please update your serverproperty table
Changed: OnlineStatusUpdate is now by default integrating Portal fields
> Maintenance PR

- GameServer/commands/gmcommands/mob.cs
Moved content of else branch in MobCommandHandler.copy() one level up, so the mob is actually created if an NPCTemplate is present
Closes #224
> /mob copy creates mob again

- GameServer/packets/Client/168/NPCCreationRequestHandler.cs
- GameServer/packets/Client/168/ObjectInteractRequestHandler.cs
- GameServer/packets/Client/168/PlayerTargetHandler.cs
I added code to remove npc which is not in the update range when the client do something with it
> fix an issue with NPCCreationRequestHandler in v1.126

- GameServer/packets/Client/168/CharacterCreateRequestHandler.cs
Fix the character creation with version 1.126
> fix 1.126 character creation & delete

- GameServer/language/EN/Language-EN.txt
- GameServer/packets/Client/168/RegionListRequestHandler.cs
> Fix guild commands not working

- GameServer/events/GameEventMgr.cs
Make GlobalHandlerCollection public (again)
> Fix GameEventMgr.GlobalHandlerCollection

- GameServer/gameobjects/GameNPC.cs
Fixes Dawn-of-Light/Storm-issues#1
> Fix Naked Script NPCs

- DOLConfig/DOLConfig.csproj
- DOLDatabase/DOLDatabase.csproj
- GameServer/gameutils/ScriptMgr.cs
The compatibility layer in version 8 introduces a big performance impact
> Downgrade MySql.Data to 6.10.9

- GameServer/gameobjects/GamePlayer.cs
- GameServer/gameutils/TempPropertiesManager.cs
- GameServer/packets/Client/168/PlayerInitRequestHandler.cs
- GameServer/serverproperty/ServerProperties.cs
Allowing tempproperties to be registered and reapplied on player connect
> TempProp Manager

- GameServer/commands/admincommands/Account.cs
> Fix command /account movecharacter

- GameServer/effects/GameEffectList.cs
- GameServer/effects/GameSpellEffect.cs
> Prevent duplication of PlayerXEffect in database

- .github/workflows/test_net48_linux.yml
- README.md
Add Github Actions badge to README.md
Change description of AppVeyor and Travis to reflect what they are for
> Add DOL.Integration tests to Github CI

- GameServerScripts/dbupdater/insert/Regions.xml
Remove regions with no zones from Regions.xml
> Fix WeatherManager on Startup

- GameServer/packets/Client/168/CryptKeyRequestHandler.cs
- GameServer/packets/Client/168/UDPPingRequestHandler.cs
- GameServer/packets/Server/IPacketEncoding.cs
- GameServer/packets/Server/PacketEncoding1110.cs
- GameServer/packets/Server/PacketEncoding168.cs
- GameServer/packets/Server/PacketProcessor.cs
some code is taken from ~~https://github.com/dol-leodagan/uthgard-opensource~~ https://github.com/thekroko/uthgard-opensource (Metty)
not tested with every versions of game.dll
> fix Packet encryption for 1.110+ and UDP handling

- appveyor.yml
Update Appveyor Deploy Token to newest github format.
> Update appveyor.yml Deploy Token

- DOLBase/Config/XMLConfigFile.cs
Previously a single tag would "eat" every following tag
> Fix bug with single tag in serverconfig.xml

- GameServer/gameutils/ServerListUpdate.cs
ServerListUpdate : use standard UrlEncode from library to handle all special characters
Previous method was only handling the space character.
See https://www.w3schools.com/tags/ref_urlencode.ASP for all the possible cases.
> ServerListUpdate : use standard UrlEncode from library

- GameServer/gameutils/ServerListUpdate.cs
ServerListUpdate fix : only apply URL encode to user and password to make it working :)
> ServerListUpdate fix : only apply URL encode to user and password

- GameServer/gameutils/Skill/Delve/StyleDelve.cs
- GameServer/packets/Client/168/DetailDisplayHandler.cs
Send proc spell description
Change order so procs are sent before the style
> Fix Style proc display

- DOLDatabase/DOLDatabase.csproj
- DOLDatabase/Handlers/MySQLObjectDatabase.cs
- Net5/DOLDatabase/DOLDatabase.csproj
- Tests/IntegrationTests/Database/DatabaseTests.cs
- Tests/IntegrationTests/Database/MySQLDBSetUp.cs
Fix MariaDB 10.6+ not working
Fix utf8 databases with special characters
> Replace MySql.Data with MySqlConnector

- GameServer/packets/Client/168/warmapshowrequesthandler.cs
> Fix WarMap Teleport

- GameServer/packets/Client/168/RegionChangeRequestHandler.cs
Remove saving of ZonePoint to DB when missing and log error instead
> Fix jump/zone points for 1.126+

- .github/Docker/Dockerfile
Replace jq script with prepared query
Remove database init step
> Use prepared database in Docker

- GameServer/gameobjects/GamePlayer.cs
- GameServer/gameutils/Skill/Delve/SpellDelve.cs
- GameServer/spells/BuffShear.cs
- GameServer/spells/HoTSpellHandler.cs
- GameServer/spells/Masterlevel/Banelord.cs
- GameServer/spells/Masterlevel/Battlemaster.cs
- GameServer/spells/Masterlevel/Convoker.cs
- GameServer/spells/Masterlevel/MasterLevelBase.cs
- GameServer/spells/Masterlevel/Perfecter.cs
- GameServer/spells/Masterlevel/Sojourner.cs
- GameServer/spells/Masterlevel/Spymaster.cs
- GameServer/spells/Masterlevel/Stormlord.cs
- GameServer/spells/Masterlevel/Warlord.cs
- GameServer/spells/PropertyChangingSpell.cs
- GameServer/spells/Valkyrie/PowerRendSpellHandler.cs
- GameServer/spells/WaterBreathingSpellHandler.cs
- Tests/UnitTests/FakeServer.cs
- Tests/UnitTests/GameObject/UT_GamePlayer.cs
Replace GamePlayer.CreateTestableGamePlayer(..) with .CreateDummy(..)
Create dummy for SpellDelve to avoid null exceptions
> Add/Fix ShortDescriptions for Masterlevels

- DOLBase/DOLBase.csproj
- DOLBase/Network/UPnPNat.cs
- GameServer/gameutils/DOLScriptCompiler.cs
- GameServer/gameutils/ServerListUpdate.cs
- GameServer/gameutils/Util.cs
- GameServer/packets/Client/168/LoginRequestHandler.cs
- GameServerScripts/dbupdater/AutoXMLDatabaseUpdate.cs
- GameServerScripts/web/OnlineStatusUpdate.cs
- NetCore/GameServer/gameutils/DOLScriptCompiler.cs
Replace RNGCryptoServiceProvider with RandomNumberGenerator
Replace MD5CryptoServiceProvider with MD5
Replace SHA256Managed with SHA256
Replace WebRequest/WebClient with HttpClient
Add reference to System.Net.Http to DOLScriptCompilers
> Replace deprecated classes for Net6

- GameServer/ai/brain/Animist/TurretBrain.cs
- GameServer/gameobjects/Animist/TurretPet.cs
Turret spells should no longer fail when target runs behind turret
> Fix animist turret when target is running through

- DOLBase/DOLBase.csproj
- DOLDatabase/DOLDatabase.csproj
- DOLDatabase/Handlers/SQLiteObjectDatabase.cs
- DOLServer/DOLServer.csproj
- GameServer/GameServer.csproj
- GameServerScripts/GameServerScripts.csproj
- NetCore/DOLBase/DOLBase.csproj
- NetCore/DOLDatabase/DOLDatabase.csproj
- NetCore/DOLServer/DOLServer.csproj
- NetCore/GameServer/GameServer.csproj
- NetCore/GameServerScripts/GameServerScripts.csproj
- NetCore/Tests/Tests.csproj
- Tests/Tests.csproj
log4net 2.0.13 -> 2.0.14
Microsoft.Data.Sqlite 5.0.12 -> 6.0.5
MySqlConnector 2.0.0 -> 2.1.10
Microsoft.Diagnostics.Runtime 2.0.226801 -> 2.1.327703
Microsoft.CodeAnalysis.CSharp 4.0.1 -> 4.2.0
Microsoft.Diagnostics.Runtime 2.0.226801 -> 2.1.327703
System.Diagnostics.PerformanceCounter 6.0.0 -> 6.0.1
Microsoft.NET.Test.Sdk 17.0.0 -> 17.2.0
NUnit 3.13.2 -> 3.13.3
NUnit3TestAdapter 4.1.0 -> 4.2.1
> Update Nuget package versions

- DOLDatabase/DOLDatabase.csproj
- DOLDatabase/Handlers/SQLiteObjectDatabase.cs
- NetCore/DOLDatabase/DOLDatabase.csproj
This reverts commit 93a3d8ba766983d5f8d7e765f4601413cacb8afe.
This fixes startup on Windows with SQLite DB
> Revert "Update Microsoft.Data.Sqlite to 6.0.5"

- GameServer/gameutils/DOLScriptCompiler.cs
- NetCore/GameServer/gameutils/DOLScriptCompiler.cs
- Tests/IntegrationTests/GameServer/gameutils/Test_DOLScriptCompiler.cs
Add GameServerScripts.dll reference after compilation
Add (explicit) DOLScriptCompiler tests
> Fix /code command

- GameServer/gameobjects/GameNPC.cs
- GameServer/keeps/AbstractGameKeep.cs
- GameServer/keeps/Gameobjects/Guards/GameKeepGuard.cs
Fix MissionMaster respawn at spawnpoint instead of last location 
Make RespawnTimerCallback() use Spawn()
> Add GameNPC.Spawn()

- GameServer/ai/brain/BD Pets/BDPetBrain.cs
- GameServer/ai/brain/ControlledNpcBrain.cs
- GameServer/gameobjects/GamePet.cs
Make spells available to GamePet
Fix Bonedancer hybrid subpets when commander is a caster
> Fix casting GamePets

- GameServer/ai/brain/DragonBrain.cs
- GameServer/ai/brain/GuardBrain.cs
- GameServer/ai/brain/Guards/KeepGuardBrain.cs
- GameServer/ai/brain/StandardMobBrain.cs
- GameServer/spells/Masterlevel/Convoker.cs
- GameServer/spells/negative/FriendBrain.cs
Set initial aggro of 'added' mobs to 1
> Fix aggro management on stun/mezz

- GameServer/commands/playercommands/LFG.cs
- GameServer/commands/playercommands/broadcast.cs
- GameServer/commands/playercommands/group.cs
- GameServer/commands/playercommands/guildchat.cs
- GameServer/commands/playercommands/invite.cs
- GameServer/commands/playercommands/random.cs
- GameServer/commands/playercommands/region.cs
- GameServer/commands/playercommands/roll.cs
- GameServer/commands/playercommands/say.cs
- GameServer/commands/playercommands/send.cs
- GameServer/commands/playercommands/trade.cs
- GameServer/commands/playercommands/train.cs
- GameServer/commands/playercommands/whisper.cs
- GameServer/commands/playercommands/yell.cs
- GameServer/language/EN/Commands/PlayerCommands.txt
I have removed the hard coded text and added all english translations into PlayerCommands.txt.
> moved hard coded text from playercommands into language file.

- .github/workflows/create_release.yml
- .github/workflows/docker_build_push.yml
- .github/workflows/extensive_test_runner.yml
- .github/workflows/test_runner.yml
Replace deprecated set-output with GITHUB_ENV
> Update Github Actions

- GameServer/gameutils/PlayerStatistics.cs
- GameServer/language/EN/GameUtils/PlayerStatistics.txt
PlayerStatistics translation with new language file under GameUtils/PlayerStatistics.txt
> PlayerStatistics translated / new language file created.

- DOLDatabase/Handlers/MySQLObjectDatabase.cs
Remove SslMode=None from ConnectionString
> Fix MySQL database connection

- old/DOLBase/DOLBase.csproj
- old/DOLDatabase/DOLDatabase.csproj
- old/DOLServer/DOLServer.csproj
- old/GameServer/GameServer.csproj
- old/GameServerScripts/GameServerScripts.csproj
- old/Tests/Tests.csproj
> Update dependencies in NetFramework

- DOLServer/DOLServer.csproj
- Tests/Tests.csproj
> Remove windows targetting for NetCore

- GameServer/gameobjects/GamePlayer.cs
Automatically increase CLs when appropriate, rather than having to go to town to talk to the king.
> Auto Level CLs

- GameServer/realmabilities/effects/DivineInterventionEffect.cs
The targets are supposed to heal themselves from the pool
> Fix Divine Intervention

- GameServer/packets/Client/168/PlayerPositionUpdateHandler.cs
- GameServer/packets/Server/PacketLib1124.cs
- GameServer/packets/Server/PacketLib173.cs
Previously there was one too many chamber displayed
Add empty chamber if spell has no corresponding model 
Remove chamber effect packet spam
> Fix Warlock Chamber Display

- .github/workflows/create_release.yml
DOLConfig couldn't find DOLServer.dll
> Fix DOLConfig

- GameServer/gameobjects/GameNPC.cs
- GameServer/propertycalc/MaxSpeedCalculator.cs
Fix pets only slowly following when owner stands
Adjust mob speeds to be closer to player speeds
> Fix pet speed

- GameServer/ai/brain/ControlledNpcBrain.cs
- GameServer/commands/gmcommands/npc.cs
- GameServer/commands/gmcommands/walk.cs
- GameServer/gameobjects/GameNPC.cs
- GameServer/packets/Server/PacketLib168.cs
- GameServer/spells/Masterlevel/Sojourner.cs
- GameServer/spells/negative/FearBrain.cs
- GameServerScripts/gameevents/FollowingNPC.cs
Also add pathing for Goto, Here and several other commands
> Enable NavMesh Pathing for Following/Attacking

- .github/workflows/create_release.yml
This release includes path finding option for mobs thanks to @jeremv42
You still need generated NavMeshes.
These can be built via https://github.com/thekroko/uthgard-opensource/tree/master/pathing/buildnav
> Bump version to 2.1.0

- DOLDatabase/WhereClause.cs
- GameServer/world/WorldMgr.cs
- Tests/UnitTests/UT_Util.cs
- Tests/UnitTests/UT_WhereClause.cs
Add WhereClause.IsNotIn (again)
Simplify WhereClause
> Fix DISABLE_REGIONS property

- DOLBase/DOLBase.csproj
- DOLDatabase/DOLDatabase.csproj
- DOLDatabase/WhereClause.cs
Make them usable by Net Framework projects like DOLToolbox
> Downgrade DOLDatabase and DOLBase to netstandard2.0

- GameServer/gameobjects/GameObject.cs
- GameServer/gameobjects/GamePlayer.cs
Previously /leave would leave the player stuck
which would make admin intervention necessary
> Fix Instance Dungeons
